package com.hassan.gestiondestock.Exeptions;

public enum ErrorsCodes {

    ARTICLE_NOT_FOUND(1000),
       ARTICLE_NOT_VALID_FOUND(1001),
    CATEGORY_NOT_FOUND(2000),
       CATEGORY_NOT_VALID_FOUND(2001),
    CLIENT_NOT_FOUND(3000),
       CLIENT_NOT_VALID_FOUND(3001),
    COMMANDE_CLIENT_NOT_FOUND(4000),
       COMMANDE_CLIENT_NOT_VALID_FOUND(4001),
    COMMANDE_FOURNISSEUR_NOT_FOUND(5000),
       COMMANDE_FOURNISSEUR_NOT_VALID_FOUND(5001),
    ENTREPRISE_NOT_FOUND(6000),
       ENTREPRISE_NOT_VALID_FOUND(6001),
    FOURNISSEUR_NOT_FOUND(7000),
       FOURNISSEUR_NOT_VALID_FOUND(7001),
    LIGNE_COMMANDE_CLIENT_NOT_FOUND(8000),
       LIGNE_COMMANDE_CLIENT_NOT_VALID_FOUND(8001),
    LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND(9000),
       LIGNE_COMMANDE_FOURNISSEUR_NOT_VALID_FOUND(9001),
    LIGNE_VENTE_NOT_FOUND(10000),
       LIGNE_VENTE_NOT_VALID_FOUND(10001),
    MVT_STOCK_NOT_FOUND(11000),
       MVT_STOCK_NOT_VALID_FOUND(11001),
    UTILISATEUR_NOT_FOUND(12000),
       UTILISATEUR_NOT_VALID_FOUND(12001),
    VENTE_NOT_FOUND(13000),
       VENTE_NOT_VALID_FOUND(13001);

    private int code;
    ErrorsCodes(int code){
      this.code=code;
    };

    public int getCode() {
        return code;
    }
}
